version: '2'
services:
  web:
    environment:
      - DEBUG=1
      - ENVIRONMENT=development      
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "80:5000"
    volumes:
     - .:/code
volumes:
  my-datavolume: